### ISSUE TITLE
Documentation has dead links for activating storage drivers

### ISSUE THREAD

**Issue by cantbewong** [codedellemc/rexray#336] opened 2016-03-06 06:04 UTC
Various (all) places in this markdown file
https://github.com/emccode/rexray/blob/master/.docs/user-guide/storage-providers.md

Links to a document that does not exist at this time in the repository:
https://github.com/emccode/rexray/blob/master/user-guide/config#storage-drivers

**Comment by akutz** [comment] 2016-03-07 16:39
Hi @cantbewong,

Thanks for finding this. The MD files should not be accessed directly in the Github repo. They're there to build the RTD docs at http://rexray.readthedocs.org/en/stable/. In fact, if you look at http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/, and scroll to the same link, it works there. 

I'm not going to close this yet. I'm going to see if there's a doc link style that will work for RTD & still work when accessing docs via the GH Repo. If not though, this is still by design, and we do point users to the RTD site from the GH Repo's main page:

![image](https://cloud.githubusercontent.com/assets/101085/13575944/e7da3c44-e450-11e5-84f9-ebf30b075a13.png)


Still, thank you again for finding the issue.

**Comment by akutz** [comment] 2016-03-07 16:51
Hi @cantbewong,

So after looking the at the MD source:

```
### Activating the Driver
To activate the EC2 driver please follow the instructions for
[activating storage drivers](/user-guide/config#storage-drivers),
using `ec2` as the driver name.
```

I found that I can adjust it so that the link looks like this:

```
[activating storage drivers](/user-guide/config.md#storage-drivers),
```

And Mkdocs still generates the appropriate HTML for the RTD site. However, the issue is that Github will still barf because the real problem is that there is a path difference between GH and RTD. Here's the produced URL in RTD:

### RTD Link
```
http://rexray.readthedocs.org/en/stable/user-guide/config#storage-drivers
```

### Github Link
```
https://github.com/emccode/rexray/blob/master/user-guide/config#storage-drivers
```

Even after I change the source to use `config.md` and the Github Link becomes `https://github.com/emccode/rexray/blob/master/user-guide/config.md#storage-drivers`, it still fails.

The failure is due to the fact that on Github the docs are in their source location (from the root) `.docs`. 

Thus if we adjust the above GH link to `https://github.com/emccode/rexray/blob/master/.docs/user-guide/config.md#storage-drivers`, it works.

I'm not sure we can make this work on both sites, but I'll search for similar issues on the RTD site and/or open one to see if I can provoke them into figuring out a way to make the links work on both sites.

**Comment by akutz** [comment] 2016-03-07 17:02
Hi @cantbewong,

I think I've found a solution. I'll have to go through ALL the docs to verify nothing is missed, but if I change the link from:

```
/user-guide/config#storage-drivers
```

to

```
config.md#storage-drivers
```

it works.

Or if we wanted to link to the `/dev-guide/build-reference/#build-binary` from `/user-guide/storage-providers/` we'd create the link to look like:

```
../dev-guide/build-reference.md#build-binary
```

The rules to make this work are:

1. All links must be relative.
2. All links must include the `.md` filename suffix for markdown files.

I'm going to volunteer you and @clintonskitson to verify the docs once I have them updated on the branch at https://github.com/akutz/rexray/blob/bugfix/doc-gh-url-fix. I'll open a PR when things are ready for review.

**Comment by akutz** [comment] 2016-03-07 18:35
FYI - The PR also includes [updated Project Guidelines](https://github.com/akutz/rexray/blob/bugfix/doc-gh-url-fix/.docs/dev-guide/project-guidelines.md#markdown) to reflect how to create links when writing markdown.

**Closed** 2017-03-02 03:04 UTC
Labels: cleanup/close, documentation
