### ISSUE TITLE
docker volume create doesn't support multiple options in options map

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#707] opened 2017-02-02 18:20 UTC
When creating volumes through the docker volume command and providing multiple options in the options map, rexray fails to create a volume.

**rexray version:**
```
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a20a838ca70838a914b632637398824fcb10d0db
Formed: Mon, 23 Jan 2017 15:14:32 UTC

libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 15:14:12 UTC
```

**command that failed:**
```
[root@rexray-aws1 ~]# docker volume create -d rexray/ebs test_vol -o=volumetype=io1,size=16,iops=200
Error response from daemon: create test_vol: VolumeDriver.Create: {"Error":"error creating volume"}
```

**command that succeeded:**
```
[root@rexray-aws1 ~]# docker volume create -d rexray/ebs test_vol -o=size=8
test_vol
```

**rexray log from time of creating volume**
```
time="2017-02-02T18:13:43Z" level=debug msg="/VolumeDriver.Create" host="unix:///var/run/libstorage/565205269.sock" pluginResponse={test_vol map[volumetype:io1,size=16,iops=200]} time=1486059223838
time="2017-02-02T18:13:43Z" level=debug msg="creating volume" host="unix:///var/run/libstorage/565205269.sock" opts=&{<nil> <nil> <nil> 0xc420663f30 <nil> <nil> map[volumetype:io1,size=16,iops=200]} time=1486059223838 volumeName="test_vol"
time="2017-02-02T18:13:43Z" level=info msg="creating volume" IOPS=0 availabilityZone= host="unix:///var/run/libstorage/565205269.sock" integrationDriver=linux opts=&{<nil> <nil> <nil> 0xc420663f30 <nil> <nil> map[volumetype:io1,size=16,iops=200]} osDriver=linux service=ebs size=16 storageDriver=libstorage time=1486059223857 volumeName="test_vol" volumeType="io1,size=16,iops=200"
time="2017-02-02T18:13:43Z" level=debug msg="waiting on executor lock" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" integrationDriver=linux osDriver=linux server=surf-trader-bb service=ebs storageDriver=libstorage time=1486059223858 txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="signalling executor lock" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" integrationDriver=linux osDriver=linux server=surf-trader-bb service=ebs storageDriver=libstorage time=1486059223910 txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="xli localdevices success" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" integrationDriver=linux osDriver=linux server=surf-trader-bb service=ebs storageDriver=libstorage time=1486059223910 txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=info msg="http request" host="unix:///var/run/libstorage/565205269.sock" route=volumeCreate server=surf-trader-bb time=1486059223910 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added route middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=post-args-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added route middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=schema-validator route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added route middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=storage-session-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added route middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=service-validator route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=transaction-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=local-devices-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=instanceIDs-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=error-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false 
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=transaction-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="added global middleware" host="unix:///var/run/libstorage/565205269.sock" middleware=query-params-handler route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="http header" Libstorage-Tx="txID=f35b4759-1368-47e8-4c1b-15f5a6661a46, txCR=1486059223" host="unix:///var/run/libstorage/565205269.sock" route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false
time="2017-02-02T18:13:43Z" level=debug msg="http header" Libstorage-Instanceid=[ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2] host="unix:///var/run/libstorage/565205269.sock" route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="http header" Libstorage-Localdevices=[ebs=/dev/xvda::/dev/xvda] host="unix:///var/run/libstorage/565205269.sock" route=volumeCreate server=surf-trader-bb time=1486059223911 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="getting storage service" host="unix:///var/run/libstorage/565205269.sock" route=volumeCreate server=surf-trader-bb service=ebs time=1486059223911 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="using cached ebs service" cacheKey=474c3062f9be20b6f3bf26586bdc00fc
time="2017-02-02T18:13:43Z" level=debug msg="validating schema" body="{\"name\":\"test_vol\",\"availabilityZone\":\"\",\"iops\":0,\"size\":16,\"type\":\"io1,size=16,iops=200\",\"opts\":{\"volumetype\":\"io1,size=16,iops=200\"}}" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate schema="{\n    \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n    \"$ref\": \"https://github.com/codedellemc/libstorage#/definitions/volumeCreateRequest\"\n}" server=surf-trader-bb service=ebs storageDriver=ebs time=1486059223911 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="getting task service" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs time=1486059223924 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="getting task service" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs time=1486059223925 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=info msg="executing task" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs task=0 time=1486059223925 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:43Z" level=debug msg="creating volume" driverName=ebs opts=&{0xc4202634f0 0xc4202634e8 0xc420263508 0xc420263520 <nil> <nil> map[service:ebs name:test_vol encrypted:<nil> encryptionkey:<nil> type:0xc420263520 opts:map[volumetype:io1,size=16,iops=200] availabilityzone:0xc4202634f0 iops:0xc4202634e8 size:0xc420263508]} volumeName="test_vol"
time="2017-02-02T18:13:44Z" level=error msg="error creating volume" driverName=ebs host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" opts=&{0xc4202634f0 0xc4202634e8 0xc420263508 0xc420263520 <nil> <nil> map[encrypted:<nil> encryptionkey:<nil> type:0xc420263520 opts:map[volumetype:io1,size=16,iops=200] service:ebs name:test_vol size:0xc420263508 availabilityzone:0xc4202634f0 iops:0xc4202634e8]} route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs task=0 time=1486059224169 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46 volumeName="test_vol"
time="2017-02-02T18:13:44Z" level=debug msg="task completed" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs task=0 time=1486059224169 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:44Z" level=error msg="error creating volume" driverName=ebs host="unix:///var/run/libstorage/565205269.sock" opts=&{0xc4202634f0 0xc4202634e8 0xc420263508 0xc420263520 <nil> <nil> map[encryptionkey:<nil> type:0xc420263520 opts:map[volumetype:io1,size=16,iops=200] service:ebs name:test_vol encrypted:<nil> availabilityzone:0xc4202634f0 iops:0xc4202634e8 size:0xc420263508]} route=volumeCreate server=surf-trader-bb time=1486059224169 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46 volumeName="test_vol"
time="2017-02-02T18:13:44Z" level=debug msg="removing task" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" removedAfter=0s route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs task=0 tasksLen=1 time=1486059224171 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:44Z" level=debug msg="removed task" host="unix:///var/run/libstorage/565205269.sock" instanceID="ebs=i-f7de1ea8,availabilityZone=us-west-2b&region=us-west-2" route=volumeCreate server=surf-trader-bb service=ebs storageDriver=ebs task=0 tasksLen=0 time=1486059224171 tls=false txCR=1486059223 txID=f35b4759-1368-47e8-4c1b-15f5a6661a46
time="2017-02-02T18:13:44Z" level=error msg="/VolumeDriver.Create: error creating volume" error.inner.volumeName="test_vol" error.inner.driverName=ebs error.inner.inner.inner.awsError=map[] error.inner.opts=map[AvailabilityZone:us-west-2b IOPS:0 Size:16 Type:io1,size=16,iops=200 Encrypted:<nil> EncryptionKey:<nil> Opts:map[]] error.status=500 host="unix:///var/run/libstorage/565205269.sock" time=1486059224171
```

**code that may be affecting:**
rexray docker integration:
https://github.com/codedellemc/rexray/blob/master/daemon/module/docker/volumedriver/voldriver.go#L191-L224

libstorage kv store util:
https://github.com/codedellemc/libstorage/blob/master/api/utils/utils_store.go

**Comment by codenrhoden** [comment] 2017-03-15 21:39
@cduchesne I'm not convinced this is a bug. Can you find any place in the Docker docs that say that syntax is allowed? I'm talking about `-o opt1=val1,opt2=val2` vs `-o opt1=val1 -o opt2=val2`.

If you look at the first line in your log:
`pluginResponse={test_vol map[volumetype:io1,size=16,iops=200]}`

That tells me that *our* plugin got an options map of
`map[volumetype:io1,size=16,iops=200]`. In other words, `volumetype` = `io1,size=16,iops=200`.

The Docker CLI did not break each option out of that comma separated list. I think it's just invalid syntax.

**Comment by codenrhoden** [comment] 2017-06-06 16:48
I decided to look into this a bit more...

As @cduchesne pointed out to me, the `-o` arg actually accepts a `map[]`, not a list. So I still think this is a misusage of the CLI, not a bug.

```
# docker volume create --help

Usage:	docker volume create [OPTIONS] [VOLUME]

Create a volume

Options:
  -d, --driver string   Specify volume driver name (default "local")
      --help            Print usage
      --label list      Set metadata for a volume (default [])
  -o, --opt map         Set driver specific options (default map[])
```

We can see how Docker is passing the parsed CLI args to our plugin by looking at our logs.  As I pointed out previously, when using `-o=volumetype=io1,size=16,iops=200`, the plugin sees `map[volumetype:io1,size=16,iops=200]`. It is not on us to parse this map correctly.

So how is it supposed to be done? If you use colons instead of `=`, like `-o size:1,volumetype:pool2`, that's not it either, as you end up with `Opts:map[size:1,volumetype:pool2:]` (size and volumetype should be separated by a space, and there is a weird trailing colon after the second option value).

If you use `-o` multiple times, that seems to work:
`docker volume create -d rexray test_vol6 -o size=1 -o volumetype=pool2`

```
DEBU[0594] /VolumeDriver.Create                          host=unix:///var/run/libstorage/401868762.sock pluginResponse={Name:test_vol6 Opts:map[volumetype:pool2 size:1]} time=1496766741451
DEBU[0594] creating volume                               host=unix:///var/run/libstorage/401868762.sock opts=&{AvailabilityZone:<nil> IOPS:<nil> Size:0xc420591fd0 Type:0xc420591fa0 Encrypted:<nil> EncryptionKey:<nil> Opts:map[size:1 volumetype:pool2]} time=1496766741451 volumeName=test_vol6
```
But is there a way to do it all in one?  I tried a few different permutations, and they all failed. When looking at the Docker [documentation](https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options) they are using `-o` or `--opt` multiple times.

Pasting here for convenience:

```
$ docker volume create --driver local \
    --opt type=tmpfs \
    --opt device=tmpfs \
    --opt o=size=100m,uid=1000 \
    foo

$ docker volume create --driver local \
    --opt type=btrfs \
    --opt device=/dev/sda2 \
    foo

$ docker volume create --driver local \
    --opt type=nfs \
    --opt o=addr=192.168.1.1,rw \
    --opt device=:/path/to/dir \
    foo
```

So I think my original comment from Mar 15 still holds. 

Looking at the Docker examples, I think it is possible that one could be confused by the opts where they *do* specifiy multiple options in a single `--opt`, like `--opt o=addr=192.168.1.1,rw` for NFS. But this is an NFS driver specific option, and it would be receiving a value of `o='addr=192.168.1.1,rw'`, and this would get translated directly to the NFS mount command, like `mount -t nfs -o addr=192.168.1.1,rw`. Hope that clears things up.

To wrap things up, if you need to pass multiple options, use the `--opt/-o` flag multiple times.

I'm going to close this.

**Closed by codenrhoden** 2017-06-06 16:48 UTC
Labels: bug
