### ISSUE TITLE
Docker managed plugin for Ceph ?

### ISSUE THREAD

**Issue by harpingon** [codedellemc/rexray#807] opened 2017-04-18 19:48 UTC
# Summary
When will there be a Ceph managed plugin for Docker? The front website lists it, and the docker site itself lists it, but there appears to be no plugin managed container for Ceph/rbd.

Have I overlooked it somewhere?

**Comment by kacole2** [comment] 2017-04-24 15:25
@cduchesne can you explain here what you told me at DockerCon last week?

**Comment by codenrhoden** [comment] 2017-05-30 16:37
Closing as a duplicate of #818.

The front page of REX-Ray (which I assume is the [Read the Docs](http://rexray.readthedocs.io/en/stable/) page?) lists all the storage platforms that REX-Ray supports. However, not all of these are available as Docker managed plugins. That list is found [here](http://rexray.readthedocs.io/en/stable/user-guide/docker-plugins/)

**Closed by codenrhoden** 2017-05-30 16:37 UTC
