### ISSUE TITLE
volume attach command ignores --force option

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#695] opened 2017-01-15 00:32 UTC
When attempting to attach a volume via the force method, there is no check in place to allow force option to function correctly. This is the result of scrubbing unavailable volumes from the list of volumes before processing attach command.

https://github.com/codedellemc/rexray/blob/master/cli/cli/cmds_10_volume.go#L291

**Comment by akutz** [comment] 2017-01-18 19:17
Hey @cduchesne,

I just spent 20 minutes on this before I realized this was handled a few days ago. Can you try and close issues you've filed when the associated PR is merged? Otherwise idiots like me waste time on figuring out where the problem is when it's already been fixed :)

**Closed by akutz** 2017-01-18 19:17 UTC

**Comment by cduchesne** [comment] 2017-01-19 17:58
sorry @akutz - will do
