### ISSUE TITLE
too many volumes returned

### ISSUE THREAD

**Issue by adaptivdesign** [codedellemc/rexray#351] opened 2016-04-06 14:53 UTC
I'm using the Virtualbox storage driver, when I run multiple machines, it creates multiple virtualbox disks. It looks like RexRay picks up any virtualbox disk. If I inspect the 'packer-ubuntu-14.04-disk1.vmdk' volume through Docker I get this error: VolumeDriver.Get: {"Error":"too many volumes returned"}. Which is because there are two volumes with the same name.

```
> docker volume ls

local               32a94cff881e8545d4c1a60d659b4b785dce6afcc5cc30058b57e211c36c7809
rexray              packer-ubuntu-14.04-disk1.vmdk
rexray              packer-ubuntu-14.04-disk1.vmdk
```

```
> rexray volume

- name: packer-ubuntu-14.04-disk1.vmdk
  volumeid: 3bbdd001-211f-4800-a82e-73173ee95607
  availabilityzone: ""
  status: /Users/raymond/VirtualBox VMs/vagrant_master-0_1459937297096_17980/packer-ubuntu-14.04-disk1.vmdk
  volumetype: ""
  iops: 0
  size: "39"
  networkname: ""
  attachments:
  - volumeid: 3bbdd001-211f-4800-a82e-73173ee95607
    instanceid: c68a2419-62c0-4c29-b124-2d3c62a6705b
    devicename: /dev/sda3
    status: /Users/raymond/VirtualBox VMs/vagrant_master-0_1459937297096_17980/packer-ubuntu-14.04-disk1.vmdk
- name: packer-ubuntu-14.04-disk1.vmdk
  volumeid: 85564279-8145-4450-9db1-2a1e0bfa0015
  availabilityzone: ""
  status: /Users/raymond/VirtualBox VMs/vagrant_node-0_1459941887608_83510/packer-ubuntu-14.04-disk1.vmdk
  volumetype: ""
  iops: 0
  size: "39"
  networkname: ""
  attachments:
  - volumeid: 85564279-8145-4450-9db1-2a1e0bfa0015
    instanceid: eb671b09-aa38-4824-bf93-d94693a6a471
    devicename: ""
    status: /Users/raymond/VirtualBox VMs/vagrant_node-0_1459941887608_83510/packer-ubuntu-14.04-disk1.vmdk
```

Is it possible for rexray to ignore these volumes?

**Comment by akutz** [comment] 2016-04-06 15:59
Hi @adaptivdesign,

For a workaround, can you create the disks manually to avoid the duplication of names? Using the VirtualBox storage manager this should be possible. 

In the meantime I am working on a patch...

**Comment by akutz** [comment] 2016-04-06 16:57
Hi @adaptivdesign,

Here's [a binary](https://dl.bintray.com/akutz/rexray/support/0.3.2+1+docker-use-first-vol/) I built for Darwin (OS X) with the patch described in PR #352. To use the patched binary, please edit your REX-Ray `config.yml` and create a root config key named `docker:` if it does not exist, and then add the following child key so that the end-result looks like this (the example does not take into account existing keys you may have):

```
docker:
  useFirstVolume: true
```

**Comment by clintonskitson** [comment] 2016-04-07 00:14
@adaptivdesign I am not sure if I'm a fan of solving for this problem. Since there is no way to determine which volume to which the query refers (if multiple with same name), it doesn't seem to make sense that we would enable any type of operation in this case. 

To me the real solve has to do with ensuring a globally unique identifier accommodates volumes in Docker.

Can you describe more about what you're trying to achieve with accessing the specific OS volume? An alternative would also be to manipulate the name of the volume through the vbox cli.

**Comment by adaptivdesign** [comment] 2016-04-07 19:42
@clintonskitson no no I completely agree with you. I don't expect anything else then the current behaviour. If 2 or more volumes exist and I want to inspect one, I totally understand an error occurs. The problem is, that I'm using the Docker API and it simply lists all volumes, which in turn will be inspected by my code.

Mayby the problem isn't clear **I did not add these 2 volumes**. On a fresh install in a virtualbox vm, when I list the docker volumes, or by calling rexray volumes, I already see these 2 volumes (depending on the amount of machines I'm running they will increase). To me it looks like they are picked up by the rexray driver automatically.

**Comment by clintonskitson** [comment] 2016-04-07 19:46
So I get what is happening, but I am unsure as to why you would want to use
the base OS virtual disks with rexray. As far as listing the volumes is it
causing a problem seeing the volumes in the list of all volumes?

A filter could possibly be introduced in the VirtualBox driver but it
doesn't seem necessary unless it is causing functionality problems.

**Comment by akutz** [comment] 2016-04-07 19:51
Hi Guys,

To be clear, you can totally control the disks virtual box creates. You may have to create them manually or rename them, but even though you didn't name them, you can control the situation pre or post. 

Regarding the "fix", I agree it's not ideal. I was simply trying to create a workaround for @adaptivdesign in order for him to continue testing REX-Ray. But you're absolutely correct @clintonskitson, volume names should be unique as far as Docker is concerned.

However.

(you knew it was coming)

Volume names do NOT have to be unique as far as many storage platforms are concerned (virtual box included). In fact, Virtualbox uses UUIDs as its disk (or volume to us) ID.

Would there be an issue with us simply returning the volume ID to docker instead of the name? Sure, the user would have to keep track of that and it's more difficult to do for them, but that may be required for driver-specific cases such as Virtualbox where the volume name is not unique.

**Comment by adaptivdesign** [comment] 2016-04-07 19:51
Me neither, I don't want to use the base os virtual disks. It's just that they are already there listed as a volume (I didn't add them as a docker volume). This causes problems

**Comment by adaptivdesign** [comment] 2016-04-07 19:53
Thank you @akutz. No no I will definitely keep using RexRay, i prefer it very much above Flocker or anything else. To me this seems like a problem with the Virtualbox Driver and the vboxwebsrv.

**Comment by akutz** [comment] 2016-04-07 19:54
Hi @clintonskitson,

Would a possible fix for this be to include a virtualbox driver option that allows you to toggle between the Disk name and ID as the value returned to Docker as the "name".

**Comment by clintonskitson** [comment] 2016-04-07 19:55
The issue of having everything that a storage platforms has be advertised
to docker is something we are addressing separately. We believe that
optionally you should be able to decide which volumes get advertised to
which container run times or clusters.

@akutz Knew you would get there =) The problem is that docker only returns
name through the API today, and yes we could manipulate the field and use
it in whatever way we want.

But if someone creates a volume via docker then you would assume the name
returned from ls would be there volume name and not the ID.

IMO for Docker, a uniqueness param as part of the API is needed to really
properly address the notion of multiple volumes w same name.

**Comment by akutz** [comment] 2016-04-07 19:58
I have an idea. So the virtualbox driver works by creating a virtual disk. Why don't we make the driver ALWAYS prefix disks it creates with something like `libstorage-` so that when it comes time to list available disks we know which ones are there specifically for purposes of REX-Ray and libStorage? We can simply remove the prefix before sending it back to Docker and always add the prefix when Docker wants to inspect a disk.

**Comment by clintonskitson** [comment] 2016-04-07 20:03
I am assuming you are referring to the Dublin branch where we implemented
this at a higher level. Yeah it would be useful for rexray to be able to
configure a prefix as part of the module config that specifies which
prefixes are valid to return and create with.

**Comment by akutz** [comment] 2016-04-07 20:05
Hi @clintonskitson,

I could have meant that, but in this case I simply meant specifically for this driver.

**Comment by adaptivdesign** [comment] 2016-04-07 20:15
Don't want to interrupt you guys, but it seems my case seems to behave different than intended. I ran https://github.com/jonasrosland/vagrant-rexray . If i run "rexray volume" it outputs all vbox disks on my host machine, if I run "docker volume ls" it shows no single rexray volume (expected behaviour). 

I will try to narrow down the problem. If it persists, I'll make a vagrant box to replicate the issue. Ok?

**Comment by clintonskitson** [comment] 2016-04-08 04:28
@adaptivdesign What you are seeing is likely due to the Docker version. In Docker 1.10, the `docker volume ls` functionality was changed to display all volumes from the storage platform. Previous to that Docker would only return volumes that Docker had previously made contact with. This was done because the source of truth for volumes was taking place in two separate locations and changes to the storage platform would cause Docker to malfunction when trying to use the same volume name again.

**Comment by clintonskitson** [comment] 2016-04-08 04:30
@akutz It could be driver level implementation but then if something at a global level was implemented, it might conflict or be confusing when individual drivers were also mutating the volume names.

I believe the only volume name manipulation in the drivers today is in ScaleIO where we shrink to 31 chars.

**Comment by adaptivdesign** [comment] 2016-04-08 12:17
@clintonskitson Thank you a lot, that clears everything up!

**Closed** 2017-03-02 03:04 UTC
Labels: cleanup/close, feature request
