### ISSUE TITLE
Support Azure Managed Disks

### ISSUE THREAD

**Issue by pjdayton** [codedellemc/rexray#1023] opened 2017-09-11 17:59 UTC
# New Feature
Currently there is only support for unmanaged disks.  Azure virtual machines deployed with managed disks are not compatible with unmanaged volumes.  

Rexray also lacks support for scale sets, as the libstorage driver cannot connect managed disks to scale set instances. 

Including support for this feature would allow for much broader use of rexray within Azure.

**Comment by rajpolaris** [comment] 2017-09-21 02:56
++1

**Comment by codenrhoden** [comment] 2017-09-26 21:25
This is a duplicate of #806.

**Closed by codenrhoden** 2017-09-26 21:25 UTC
